### ISSUE TITLE
Template setting traps you in flag

### ISSUE THREAD

**Issue by mxmeinhold** [ComputerScienceHouse/quotefault#37]
When selecting a template, it is possible to go from bootstrap to flag and this setting will be saved. It is not however possible to go from flag to bootstrap.
```
Bad Request
The browser (or proxy) sent a request that this server could not understand.
```
This leaves me trapped with the flag template, and no way to return to my lovely land of themes galore.

**Comment by dantayy** [comment]
#50 Can't get trapped in the flag template if it doesn't exist!
