### ISSUE TITLE
Can't delete a quote

### ISSUE THREAD

**Issue by sgreene570** [ComputerScienceHouse/Quotefault#47]
would be cool if you could delete a quote that you submitted (or maybe additionally a quote that you were quoted saying)

**Comment by mfrancis95** [comment]
To add to this, when deleting a quote, I think the quote shouldn't be deleted for good. It should simply be marked as deleted so it won't show up in searches. That way we can recover "deleted" quotes.

**Comment by sgreene570** [comment]
+1
